- name: install mysql
  hosts: server
  become: yes
  tasks:
    - name: run apt-get update
      apt:
       update_cache: yes
    - name: install mysql
      apt:
        name: mysql-server
        state: present
    - name: start service
      systemd:
        name: mysql
        state: restarted
